### PR TITLE
Sync latest updates to CVMix/CVMix-src 

### PR DESCRIPTION
**Pull request by mnlevy1981**
We made a few more changes for StokesMOST that we'd like to have on `dev/ncar`, which means this fork needs to be up-to-date with the upstream CVMix repository

### CODE REVIEW

**Comment by mnlevy1981** [comment]
I think clicking the "sync fork" button is better than merging in this PR, as we want to do a ff-only merge

**Comment by mnlevy1981** [comment]
Would it be possible for me to get write access to this repo? I'd be happy to sync it after accepting PRs over on the main repository

**Comment by marshallward** [comment]
Temporarily closing this to test something...

**Comment by marshallward** [comment]
Used "Sync fork", as suggested by @mnlevy1981

**Pull request closed without merging**
